package main

import (
	"flag"
	"fmt"
	"io"
	"os"
	"sort"
	"strings"
)

type completionItem struct {
	Name string
	Desc string
}

var completionCommands = []completionItem{
	{"shell", "Start interactive shell in sandbox"},
	{"run", "Run a command in sandbox"},
	{"fork", "Run in a named copied folder with Compose namespace"},
	{"setup", "Configure yolobox settings"},
	{"upgrade", "Upgrade binary/image, or inspect latest release"},
	{"update-agents", "Update bundled AI CLIs in persistent home"},
	{"config", "Print resolved configuration"},
	{"reset", "Remove named volumes"},
	{"uninstall", "Uninstall yolobox completely"},
	{"completion", "Generate shell completion script"},
	{"version", "Show version info"},
	{"help", "Show help"},
}

var completionShells = []string{"bash", "zsh"}

var completionPlatforms = []string{"linux/amd64", "linux/arm64"}

type completionFlag struct {
	Name   string
	Usage  string
	IsBool bool
	Repeat bool
}

// baseCompletionFlags introspects the real base FlagSet so completions never
// drift from the flags yolobox actually accepts.
func baseCompletionFlags() []completionFlag {
	fs, _ := newBaseFlagSet("completion")
	var flags []completionFlag
	fs.VisitAll(func(f *flag.Flag) {
		cf := completionFlag{Name: f.Name, Usage: f.Usage}
		if bf, ok := f.Value.(interface{ IsBoolFlag() bool }); ok && bf.IsBoolFlag() {
			cf.IsBool = true
		}
		if _, ok := f.Value.(*stringSliceFlag); ok {
			cf.Repeat = true
		}
		flags = append(flags, cf)
	})
	sort.Slice(flags, func(i, j int) bool { return flags[i].Name < flags[j].Name })
	return flags
}

func updateAgentCompletionTargets() []string {
	targets := append([]string{"all"}, agentUpdateTargets...)
	return append(targets, "antigravity")
}

func printCompletionUsage() {
	fmt.Fprintln(os.Stderr, "USAGE:")
	fmt.Fprintln(os.Stderr, "  yolobox completion bash    Print bash completion script")
	fmt.Fprintln(os.Stderr, "  yolobox completion zsh     Print zsh completion script")
	fmt.Fprintln(os.Stderr, "")
	fmt.Fprintln(os.Stderr, "SETUP:")
	fmt.Fprintln(os.Stderr, `  bash: echo 'eval "$(yolobox completion bash)"' >> ~/.bashrc`)
	fmt.Fprintln(os.Stderr, "  zsh:  yolobox completion zsh > \"${fpath[1]}/_yolobox\"")
	fmt.Fprintln(os.Stderr, "        or, after compinit: echo 'source <(yolobox completion zsh)' >> ~/.zshrc")
	fmt.Fprintln(os.Stderr, "")
	fmt.Fprintln(os.Stderr, "Homebrew installs both scripts automatically.")
}

func runCompletion(args []string, out io.Writer) error {
	if len(args) == 0 || args[0] == "-h" || args[0] == "--help" {
		printCompletionUsage()
		if len(args) == 0 {
			return fmt.Errorf("completion requires a shell: %s", strings.Join(completionShells, ", "))
		}
		return errHelp
	}
	if len(args) > 1 {
		return fmt.Errorf("unexpected args: %v", args[1:])
	}
	switch args[0] {
	case "bash":
		_, err := io.WriteString(out, bashCompletionScript())
		return err
	case "zsh":
		_, err := io.WriteString(out, zshCompletionScript())
		return err
	default:
		return fmt.Errorf("unsupported shell %q (expected one of: %s)", args[0], strings.Join(completionShells, ", "))
	}
}

func completionCommandNames() []string {
	names := make([]string, 0, len(completionCommands))
	for _, c := range completionCommands {
		names = append(names, c.Name)
	}
	return names
}

func bashCompletionScript() string {
	flags := baseCompletionFlags()
	var flagNames, valueFlags []string
	for _, f := range flags {
		flagNames = append(flagNames, "--"+f.Name)
		if !f.IsBool {
			valueFlags = append(valueFlags, "--"+f.Name)
		}
	}

	var b strings.Builder
	fmt.Fprintf(&b, `# bash completion for yolobox                              -*- shell-script -*-
# Generated by 'yolobox completion bash'. Load with:
#   eval "$(yolobox completion bash)"

__yolobox_value_flag() {
    case "$1" in
        %s) return 0 ;;
    esac
    return 1
}

__yolobox_complete_flag_value() {
    case "$1" in
        --runtime) COMPREPLY=($(compgen -W "docker podman container" -- "$2")) ;;
        --platform) COMPREPLY=($(compgen -W "%s" -- "$2")) ;;
        --mount|--copy-as|--customize-file)
            compopt -o filenames 2>/dev/null
            COMPREPLY=($(compgen -f -- "$2")) ;;
        *) COMPREPLY=() ;;
    esac
}

# Prints the index of the first positional word in COMP_WORDS[start..COMP_CWORD-1],
# skipping yolobox flags and their values. Prints nothing if none.
__yolobox_first_positional() {
    local i=$1 w
    while (( i < COMP_CWORD )); do
        w="${COMP_WORDS[i]}"
        case "$w" in
            --) echo $((i + 1)); return ;;
            -*=*) ;;
            -*) if __yolobox_value_flag "$w"; then ((i++)); fi ;;
            *) echo "$i"; return ;;
        esac
        ((i++))
    done
}

_yolobox() {
    local cur prev cmd pos
    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"

    local commands="%s"
    local tools="%s"
    local base_flags="%s"
    local agent_targets="%s"

    if (( COMP_CWORD == 1 )); then
        if [[ "$cur" == -* ]]; then
            COMPREPLY=($(compgen -W "$base_flags" -- "$cur"))
        else
            COMPREPLY=($(compgen -W "$commands $tools" -- "$cur"))
        fi
        return
    fi

    cmd="${COMP_WORDS[1]}"
    case "$cmd" in
        run|shell|config|update-agents|-*)
            if __yolobox_value_flag "$prev"; then
                __yolobox_complete_flag_value "$prev" "$cur"
                return
            fi
            if [[ "$cmd" == -* ]]; then
                COMPREPLY=($(compgen -W "$base_flags" -- "$cur"))
                return
            fi
            if [[ "$cmd" == run ]]; then
                pos=$(__yolobox_first_positional 2)
                if [[ -n "$pos" ]]; then
                    compopt -o default 2>/dev/null
                    COMPREPLY=()
                    return
                fi
            fi
            if [[ "$cur" == -* ]]; then
                COMPREPLY=($(compgen -W "$base_flags" -- "$cur"))
            elif [[ "$cmd" == run ]]; then
                COMPREPLY=($(compgen -c -- "$cur"))
            elif [[ "$cmd" == update-agents ]]; then
                COMPREPLY=($(compgen -W "$agent_targets" -- "$cur"))
            fi
            ;;
        fork)
            if (( COMP_CWORD == 2 )); then
                COMPREPLY=($(compgen -W "--name resume discard" -- "$cur"))
                return
            fi
            case "${COMP_WORDS[2]}" in
                resume)
                    if (( COMP_CWORD > 3 )); then
                        compopt -o default 2>/dev/null
                    fi
                    ;;
                discard)
                    COMPREPLY=($(compgen -W "--force" -- "$cur"))
                    ;;
                *)
                    [[ "$prev" == --name ]] && return
                    pos=$(__yolobox_first_positional 2)
                    if [[ -n "$pos" ]]; then
                        compopt -o default 2>/dev/null
                    elif [[ "$cur" == -* ]]; then
                        COMPREPLY=($(compgen -W "--name" -- "$cur"))
                    else
                        COMPREPLY=($(compgen -c -- "$cur"))
                    fi
                    ;;
            esac
            ;;
        upgrade)
            COMPREPLY=($(compgen -W "--check" -- "$cur"))
            ;;
        reset)
            if [[ "$prev" == --platform ]]; then
                COMPREPLY=($(compgen -W "%s" -- "$cur"))
            else
                COMPREPLY=($(compgen -W "--force --platform" -- "$cur"))
            fi
            ;;
        uninstall)
            COMPREPLY=($(compgen -W "--force --keep-volumes" -- "$cur"))
            ;;
        completion)
            (( COMP_CWORD == 2 )) && COMPREPLY=($(compgen -W "%s" -- "$cur"))
            ;;
        setup|version|help)
            ;;
        *)
            # Tool shortcuts: yolobox flags first, then args for the tool itself.
            if __yolobox_value_flag "$prev"; then
                __yolobox_complete_flag_value "$prev" "$cur"
            elif [[ "$cur" == -* ]]; then
                COMPREPLY=($(compgen -W "$base_flags" -- "$cur"))
            else
                compopt -o default 2>/dev/null
            fi
            ;;
    esac
}

complete -F _yolobox yolobox
`,
		strings.Join(valueFlags, "|"),
		strings.Join(completionPlatforms, " "),
		strings.Join(completionCommandNames(), " "),
		strings.Join(toolShortcuts, " "),
		strings.Join(flagNames, " "),
		strings.Join(updateAgentCompletionTargets(), " "),
		strings.Join(completionPlatforms, " "),
		strings.Join(completionShells, " "),
	)
	return b.String()
}

func zshQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}

func zshEscapeDesc(s string) string {
	r := strings.NewReplacer(`\`, `\\`, "[", `\[`, "]", `\]`, ":", `\:`)
	return r.Replace(s)
}

func zshFlagSpec(f completionFlag) string {
	desc := zshEscapeDesc(f.Usage)
	prefix := ""
	if f.Repeat {
		prefix = "*"
	}
	if f.IsBool {
		return zshQuote(fmt.Sprintf("%s--%s[%s]", prefix, f.Name, desc))
	}
	action := " "
	switch f.Name {
	case "runtime":
		action = "(docker podman container)"
	case "platform":
		action = "(" + strings.Join(completionPlatforms, " ") + ")"
	case "mount", "copy-as", "customize-file":
		action = "_files"
	}
	return zshQuote(fmt.Sprintf("%s--%s=[%s]:%s:%s", prefix, f.Name, desc, f.Name, action))
}

func zshDescribeItems(items []completionItem) string {
	var parts []string
	for _, item := range items {
		parts = append(parts, zshQuote(strings.ReplaceAll(item.Name, ":", `\:`)+":"+item.Desc))
	}
	return strings.Join(parts, " ")
}

func zshCompletionScript() string {
	var flagSpecs []string
	for _, f := range baseCompletionFlags() {
		flagSpecs = append(flagSpecs, "        "+zshFlagSpec(f))
	}
	var tools []completionItem
	for _, tool := range toolShortcuts {
		tools = append(tools, completionItem{tool, "Run " + tool + " in sandbox"})
	}

	return fmt.Sprintf(`#compdef yolobox
# zsh completion for yolobox
# Generated by 'yolobox completion zsh'. Install into a directory on $fpath
# as _yolobox, or load directly after compinit with:
#   source <(yolobox completion zsh)

_yolobox() {
    local -a base_flags commands tools agent_targets
    base_flags=(
%s
    )
    commands=(%s)
    tools=(%s)
    agent_targets=(%s)

    local curcontext="$curcontext" ret=1

    if (( CURRENT == 2 )); then
        if [[ "$words[CURRENT]" == -* ]]; then
            _arguments -S $base_flags && ret=0
        else
            _describe -t commands 'yolobox command' commands && ret=0
            _describe -t tools 'tool shortcut' tools && ret=0
        fi
        return ret
    fi

    local cmd="$words[2]"
    if [[ "$cmd" == -* ]]; then
        _arguments -S $base_flags && ret=0
        return ret
    fi

    shift words
    (( CURRENT-- ))
    curcontext="${curcontext%%:*:*}:yolobox-$cmd:"

    case "$cmd" in
        run)
            _arguments -S $base_flags \
                '(-)1:command:_command_names -e' \
                '*::arguments:_normal' && ret=0
            ;;
        shell|config)
            _arguments -S $base_flags && ret=0
            ;;
        update-agents)
            _arguments -S $base_flags "*:agent:($agent_targets)" && ret=0
            ;;
        fork)
            if (( CURRENT == 2 )); then
                local -a subs
                subs=('resume:Reopen an existing copied folder' 'discard:Delete a copied folder')
                _describe -t fork-commands 'fork subcommand' subs && ret=0
                compadd -- --name && ret=0
                return ret
            fi
            case "$words[2]" in
                resume)
                    if (( CURRENT == 3 )); then
                        _message 'environment name'
                    else
                        shift 3 words
                        (( CURRENT -= 3 ))
                        _normal && ret=0
                    fi
                    ;;
                discard)
                    shift words
                    (( CURRENT-- ))
                    _arguments '--force[confirm deletion]' '1:environment name: ' && ret=0
                    ;;
                *)
                    _arguments -S '--name=[developer/environment name]:name: ' \
                        '(-)1:command:_command_names -e' \
                        '*::arguments:_normal' && ret=0
                    ;;
            esac
            ;;
        upgrade)
            _arguments '--check[check latest release without upgrading]' && ret=0
            ;;
        reset)
            _arguments '--force[remove volumes]' \
                '--platform=[only remove volumes for this platform]:platform:(%s)' && ret=0
            ;;
        uninstall)
            _arguments '--force[confirm uninstall]' '--keep-volumes[keep container volumes]' && ret=0
            ;;
        completion)
            _arguments '1:shell:(%s)' && ret=0
            ;;
        setup|version|help)
            ;;
        *)
            _arguments -S $base_flags '*:: :_default' && ret=0
            ;;
    esac
    return ret
}

if [ "$funcstack[1]" = "_yolobox" ]; then
    _yolobox "$@"
else
    compdef _yolobox yolobox
fi
`,
		strings.Join(flagSpecs, "\n"),
		zshDescribeItems(completionCommands),
		zshDescribeItems(tools),
		strings.Join(updateAgentCompletionTargets(), " "),
		strings.Join(completionPlatforms, " "),
		strings.Join(completionShells, " "),
	)
}
